### ISSUE TITLE
Roadmap Mali

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-mali#13]
# 1. Identifier les recettes fiscales et dépenses publiques importantes + les autres données de calage utiles

- [ ] Partager les documents officiels/sources (dropbox, drive, ou repos git (mieux non ?))

## 1.1 Postes budgétaires et recettes fiscales

Faire une feuille récapitulative (format csv, séparateur = virgule, sans accent) comportant : 
 
- [ ] le total des **recettes fiscales** générées par impôt (utile aussi pour le **calage**)
- [ ] la **part des recettes** de chaque impôt dans les recettes totales
- [ ] un indicateur allant de 0 à 4 pour déterminer si les données disponibles permettent de calculer l'impôt correctement (0 = pas d'info; 4 = toutes les infos dispo)
- [ ] les **budgets** totaux consacrés à chaque **allocation**
- [ ] le **nombre d'individus** bénéficiant de ces allocations selon les sources différentes de l'enquête
- [ ] les **budgets** consacrés à la **santé** et à **l'éducation** (suivant la méthode de désagrégation choisie) 
- [ ] le nombre d'individus bénéficiant de ces budgets selon les sources différentes de l'enquête
- [ ] l'année de référence
- [ ] la **source**

## 1.2 Autres données de calage : 

Faire une feuille récapitulative (format csv, séparateur = virgule, sans accent) avec : 

- [ ] des données administratives/recensement sur la population (par région, nationalité etc ...) 
- [ ] des données administratives sur la production (par secteur, régions etc ...)
- [ ] des données sur les prix
- [ ] l'année de référence
- [ ] leur **source**

# 2. Explorer la législation et remplir le wiki

Liste est modifiable. Ne remplir le wiki que pour les éléments de fiscalité pertinents, i.e dont les apports budgétaires sont importants. Toujours citer ou référencer les parties pertinentes du code des impôts.

## 2.1 Impôts directs

- [ ] Impôt sur le revenu des personnes physiques
- [ ] Impôt sur le revenu des entreprises unipersonnelles 
- [ ] Autres ? 

## 2.2 Impôts indirects

- [ ] Taxe sur la valeur ajoutée 
- [ ] Taxe douanières
- [ ] Autres ? 

## 2.3 Allocation et subventions

- [ ] subvention
- [ ] pension ou rente viagère
- [ ] allocation sociale 
- [ ] allocation chômage 

# 3 Faire le lien entre les données micro et la législation

Faire un tableau de toutes les variables tirées de l'enquête (format csv, séparateur = virgule, sans accent) comportant : 
 
- [ ] une colonne rappelant les références de l'enquête (date, nom, source des données)
- [ ] une colonne précisant le nom de la variable
- [ ] une colonne précisant l'unité statistique de la variable 
- [ ] une colonne précisant l'usage que l'on va faire de cette variable : soit caractéristique socio-démographique, soit le nom le l'impôt qu'elle va servir à calculer, soit conso/revenu. 
- [ ] une colonne précisant les références des questions brutes à partir desquelles la variable a été calculée.
- [ ] un commentaire sur la méthode de calcul si pertinent
- [ ] un commentaire sur la qualité de la variable si pertinent (peut-être un indicateur ?)

# 4. Impôt sur les traitements et les Salaires (ITS)

On procède en partant de l'impôt pour remonter aux revenus primaires

## 4.1 Calcul de l'impôt #5

- [x] Création d'une variable d'impôt sur les traitements et les salaires
- [x] Création d'une variable de revenu net imposable
- [x] Création d'un paramètre donnant le barême de l'ITS
- [x] Définition d'une formule appliquant le barême d'imposition au revenu net imposable

## 4.2 Passage du montant brut de l'impôt au montant net de l'impôt

- [ ] coder les réductions familiales #24 #26 

## 4.3 Passage du montant brut du revenu imposable au montant net

Il faut déduire
- [ ] retenues faites par l'employeur en vie de la constitution de pensions ou de retraites dans la limite de 4% des salaires bruts
NB : plafond supplémentaire pour certains cas particuliers, fixé par les textes législatifs régissant ces domaines
- [ ] allocations et indemnités spéciales destinées à couvrir les frais inhérents à la fonction/l'emploi
NB : maximum déductible fixé par un arrêté (inclus dans le CGI sur le site https://www.dgi.gouv.ml/CGI/)

##  4.4 Calculer le revenu soumis à l'impôt
- [ ] montant total des traitements, salaires, pécules, indemnités, émoluments, primes, gratifications ainsi que tous autres avantages en argent/nature
payées dans l'année aux salariés par les employeurs publics ou privés
- [ ] pensions et rentes viagères
- [ ] rémunérations allouées aux dirigeants des soc par actions et rétribuant leur fonction de direction
NB : exemptions de l'art 25
- [ ] les revenus affranchis de l'impôt
NB : conditions de déductibilité sont précisées par arrêté (inclus dans le CGI sur le site https://www.dgi.gouv.ml/CGI/)

# 5. Impôts sur les entreprises unipersonnelles 

## 5.1 revenu imposable 

- [ ] définir les variables qui entrent dans le calcul du revenu imposable
- [ ] définir variables/paramètres nécessaires aux abattements
- [ ]  définir les variables/paramètres nécessaires à la prise en compte des cas d'exonérations (si applicable)

## 5.2 calcul 

- [ ] définir le barème 
- [ ]  coder la méthode de calcul
- [ ] avec les tests

# 6 taxe sur la valeur ajoutée (TVA) 

# 7 taxe douanières 

# 8. Autres impôts
